#!/bin/bash
# Deploy to Raspberry Pi.
# Run 'yarn setup-pi' first if this is the first deploy.
set -e

ROOT="$(dirname "$0")/.."
cd "$ROOT"

# Load .env
export $(grep -v '^#' .env | xargs)

PI="${PI_USER}@${PI_HOST}"
REMOTE_DIR="~/artele"

echo "==> Building React app (targeting Pi at ${PI_HOST})..."
REACT_APP_SOCKET_URL="http://${PI_HOST}:3001/" yarn build

echo ""
echo "==> Syncing to Pi..."
rsync -avz --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude 'server/node_modules' \
  --exclude 'server/data' \
  --exclude '.env' \
  --exclude 'references' \
  . ${PI}:${REMOTE_DIR}/

echo ""
echo "==> Writing production .env to Pi..."
ssh ${PI} "cat > ${REMOTE_DIR}/.env" << EOF
# Production config — generated by deploy.sh
SOCKET_PORT=3001
SOCKET_HOST=0.0.0.0
CORS_ORIGINS=*

SLACK_TOKEN=${SLACK_TOKEN}

RECEIVER_ENABLED=${RECEIVER_ENABLED}
RECEIVER_IP=${RECEIVER_IP}
RECEIVER_INPUT=${RECEIVER_INPUT}
CEC_ENABLED=${CEC_ENABLED}
EOF

echo ""
echo "==> Installing server dependencies on Pi..."
ssh ${PI} "cd ${REMOTE_DIR}/server && npm install --omit=dev"

echo ""
echo "==> Restarting app via pm2..."
ssh ${PI} "cd ${REMOTE_DIR} && pm2 restart artele 2>/dev/null \
  || pm2 start server/src/socket.server.js --name artele && pm2 save"

echo ""
echo "✓ Deployed. App running at http://${PI_HOST}:3001"
